"""empty message

Revision ID: 43d326bd4d12
Revises: d30066ba1750
Create Date: 2017-06-19 11:20:33.815128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d326bd4d12'
down_revision = 'd30066ba1750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('emails', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('traffic', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic', 'updated_at')
    op.drop_column('sales', 'updated_at')
    op.drop_column('emails', 'updated_at')
    op.drop_column('customers', 'updated_at')
    # ### end Alembic commands ###
